<?php
require_once 'auth.php';
require_once 'db_connect.php';
requireAdmin();

$configFile = __DIR__ . '/branding_config.php';
$message    = '';
$msgType    = 'info';

// ── Handle form submission ──────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_branding'])) {

    $navBg     = preg_match('/^#[0-9a-fA-F]{6}$/', $_POST['nav_bg']     ?? '') ? $_POST['nav_bg']     : '#1a252f';
    $navBorder = preg_match('/^#[0-9a-fA-F]{6}$/', $_POST['nav_border'] ?? '') ? $_POST['nav_border'] : '#0d1b24';
    $accent    = preg_match('/^#[0-9a-fA-F]{6}$/', $_POST['accent']     ?? '') ? $_POST['accent']     : '#3498db';
    $navText   = preg_match('/^#[0-9a-fA-F]{6}$/', $_POST['nav_text']   ?? '') ? $_POST['nav_text']   : '#ffffff';

    // Determine logo path — keep existing if no new file; validate to prevent path traversal
    $rawExisting = $_POST['existing_logo'] ?? '';
    $logoPath = (preg_match('/^uploads\/brand_logo\.[a-z]{2,4}$/', $rawExisting)) ? $rawExisting : '';

    if (!empty($_FILES['logo_file']['name'])) {
        $allowed = ['image/png','image/jpeg','image/gif','image/webp','image/svg+xml'];
        $ext_map = ['image/png'=>'png','image/jpeg'=>'jpg','image/gif'=>'gif',
                    'image/webp'=>'webp','image/svg+xml'=>'svg'];
        $mime = mime_content_type($_FILES['logo_file']['tmp_name']);
        if (!in_array($mime, $allowed, true)) {
            $message = 'Logo must be PNG, JPG, GIF, WEBP, or SVG.';
            $msgType = 'error';
        } else {
            $ext      = $ext_map[$mime];
            $destPath = 'uploads/brand_logo.' . $ext;
            $destFull = __DIR__ . '/' . $destPath;
            if (!move_uploaded_file($_FILES['logo_file']['tmp_name'], $destFull)) {
                $message = 'Could not save logo file. Check uploads/ folder permissions.';
                $msgType = 'error';
            } else {
                $logoPath = $destPath;
            }
        }
    }

    if ($message === '') {
        $lines  = "<?php\n";
        $lines .= "// ============================================================\n";
        $lines .= "// Store Branding Configuration\n";
        $lines .= "// Auto-generated by setup_branding.php — edit this file\n";
        $lines .= "// directly to update branding after initial setup.\n";
        $lines .= "// ============================================================\n";
        $lines .= "define('BRAND_LOGO',       " . var_export($logoPath, true) . ");\n";
        $lines .= "define('BRAND_NAV_BG',     " . var_export($navBg,    true) . ");\n";
        $lines .= "define('BRAND_NAV_BORDER', " . var_export($navBorder,true) . ");\n";
        $lines .= "define('BRAND_ACCENT',     " . var_export($accent,   true) . ");\n";
        $lines .= "define('BRAND_TEXT',       " . var_export($navText,  true) . ");\n";

        if (file_put_contents($configFile, $lines) === false) {
            $message = 'Could not write branding_config.php. Check file permissions.';
            $msgType = 'error';
        } else {
            $message = 'Branding saved. The builder will now display your store colors and logo.';
            $msgType = 'success';
        }
    }
}

// ── Read current config for display ────────────────────────
if (!defined('BRAND_LOGO'))       { require_once $configFile; }

$curLogo    = defined('BRAND_LOGO')       ? BRAND_LOGO       : '';
$curNavBg   = defined('BRAND_NAV_BG')     ? BRAND_NAV_BG     : '#1a252f';
$curBorder  = defined('BRAND_NAV_BORDER') ? BRAND_NAV_BORDER : '#0d1b24';
$curAccent  = defined('BRAND_ACCENT')     ? BRAND_ACCENT     : '#3498db';
$curText    = defined('BRAND_TEXT')       ? BRAND_TEXT       : '#ffffff';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Branding Setup — <?= htmlspecialchars(SITE_NAME) ?></title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
        body { background: #1a252f; color: #fff; display: flex; flex-direction: column; min-height: 100vh; }
        #top-nav {
            background: <?= htmlspecialchars($curNavBg) ?>; padding: 0 16px;
            display: flex; align-items: center; gap: 14px; height: 46px;
            border-bottom: 1px solid <?= htmlspecialchars($curBorder) ?>;
        }
        #top-nav .brand { font-weight: bold; font-size: 14px; color: <?= htmlspecialchars($curText) ?>; margin-right: auto; }
        #top-nav a { color: #bdc3c7; text-decoration: none; font-size: 12px; padding: 5px 9px; border-radius: 3px; }
        #top-nav a:hover { background: #2c3e50; color: #fff; }
        .page { max-width: 640px; margin: 40px auto; padding: 0 20px; }
        h1 { font-size: 22px; margin-bottom: 6px; }
        .subtitle { color: #bdc3c7; font-size: 13px; margin-bottom: 28px; }
        .card { background: #243342; border-radius: 8px; padding: 24px; margin-bottom: 20px; border: 1px solid #34495e; }
        .card h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #f39c12; margin-bottom: 16px; }
        label { display: block; font-size: 12px; text-transform: uppercase; letter-spacing: .7px; color: #bdc3c7; margin-bottom: 5px; }
        input[type="text"], input[type="file"] {
            width: 100%; padding: 9px 11px; border-radius: 4px;
            border: 1px solid #34495e; background: #1a252f; color: #fff; font-size: 14px;
            margin-bottom: 16px;
        }
        input[type="color"] { height: 36px; width: 60px; padding: 2px; cursor: pointer;
                              border: 1px solid #34495e; border-radius: 4px; background: #1a252f;
                              margin-bottom: 16px; }
        .color-row { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }
        .color-row input[type="color"] { margin-bottom: 0; flex-shrink: 0; }
        .color-row span { font-size: 13px; color: #bdc3c7; }
        .btn { padding: 10px 22px; border: none; border-radius: 4px; font-size: 14px;
               font-weight: 700; cursor: pointer; }
        .btn-primary { background: #3498db; color: #fff; }
        .btn-primary:hover { background: #2980b9; }
        .btn-back { background: #7f8c8d; color: #fff; margin-left: 10px; }
        .btn-back:hover { background: #6c7a89; }
        .msg { padding: 12px 16px; border-radius: 5px; margin-bottom: 20px; font-size: 13px; }
        .error   { background: #4a1010; color: #f5a6a6; border: 1px solid #e74c3c; }
        .success { background: #0d3320; color: #a6f5c7; border: 1px solid #27ae60; }
        .logo-preview { margin-top: 6px; margin-bottom: 16px; }
        .logo-preview img { max-height: 60px; max-width: 200px; border-radius: 4px;
                            background: rgba(255,255,255,.08); padding: 4px; }
        .note { font-size: 12px; color: #7f8c8d; margin-top: -10px; margin-bottom: 16px; }
        .preview-bar {
            border-radius: 6px; overflow: hidden; margin-bottom: 16px;
            border: 1px solid #34495e;
        }
        .preview-nav {
            display: flex; align-items: center; gap: 14px; padding: 0 16px; height: 46px;
        }
        .preview-brand { font-weight: bold; font-size: 14px; margin-right: auto; }
        .preview-link  { font-size: 12px; padding: 4px 8px; border-radius: 3px; }
    </style>
</head>
<body>
<div id="top-nav">
    <?php if ($curLogo): ?>
        <img src="<?= htmlspecialchars($curLogo) ?>" alt="Logo" style="max-height:32px; max-width:120px; object-fit:contain;">
    <?php endif; ?>
    <span class="brand"><?= htmlspecialchars(SITE_NAME) ?></span>
    <a href="builder.php">← Builder</a>
    <a href="admin_panel.php">Admin Panel</a>
    <a href="logout.php">Sign Out</a>
</div>

<div class="page">
    <h1>Store Branding Setup</h1>
    <p class="subtitle">
        Set the logo and colors displayed on the builder login screen.
        After saving, edit <code>branding_config.php</code> directly to make further changes.
    </p>

    <?php if ($message): ?>
        <div class="msg <?= $msgType ?>"><?= htmlspecialchars($message) ?></div>
    <?php endif; ?>

    <form method="POST" enctype="multipart/form-data">
        <input type="hidden" name="existing_logo" value="<?= htmlspecialchars($curLogo) ?>">

        <!-- Live preview -->
        <div class="card">
            <h2>Preview</h2>
            <div class="preview-bar" id="preview-bar">
                <div class="preview-nav" id="preview-nav"
                     style="background:<?= htmlspecialchars($curNavBg) ?>; border-bottom: 1px solid <?= htmlspecialchars($curBorder) ?>;">
                    <span id="preview-logo-wrap">
                        <?php if ($curLogo): ?>
                            <img src="<?= htmlspecialchars($curLogo) ?>" id="preview-logo-img"
                                 style="max-height:28px;max-width:100px;object-fit:contain;" alt="">
                        <?php endif; ?>
                    </span>
                    <span class="preview-brand" id="preview-brand"
                          style="color:<?= htmlspecialchars($curText) ?>;"><?= htmlspecialchars(SITE_NAME) ?></span>
                    <span class="preview-link"
                          style="background:<?= htmlspecialchars($curAccent) ?>;color:#fff;"
                          id="preview-accent-btn">Publish</span>
                    <span style="font-size:12px;" id="preview-link-text">Sign Out</span>
                </div>
            </div>
        </div>

        <!-- Logo -->
        <div class="card">
            <h2>Logo</h2>
            <?php if ($curLogo): ?>
                <div class="logo-preview">
                    <img src="<?= htmlspecialchars($curLogo) ?>" alt="Current logo">
                </div>
                <p class="note">Current: <?= htmlspecialchars($curLogo) ?></p>
            <?php endif; ?>
            <label>Upload Logo (PNG, JPG, SVG recommended)</label>
            <input type="file" name="logo_file" accept="image/*" onchange="previewLogo(this)">
            <p class="note">Leave blank to keep the current logo. Max size: 2 MB.</p>
        </div>

        <!-- Colors -->
        <div class="card">
            <h2>Colors</h2>
            <label>Nav Background</label>
            <div class="color-row">
                <input type="color" name="nav_bg" id="c_nav_bg" value="<?= htmlspecialchars($curNavBg) ?>"
                       oninput="livePreview()">
                <span>Background of the top navigation bar</span>
            </div>

            <label>Nav Border / Shadow</label>
            <div class="color-row">
                <input type="color" name="nav_border" id="c_nav_border" value="<?= htmlspecialchars($curBorder) ?>"
                       oninput="livePreview()">
                <span>Bottom border line on the nav bar</span>
            </div>

            <label>Accent Color</label>
            <div class="color-row">
                <input type="color" name="accent" id="c_accent" value="<?= htmlspecialchars($curAccent) ?>"
                       oninput="livePreview()">
                <span>Publish button and highlight color</span>
            </div>

            <label>Nav Text Color</label>
            <div class="color-row">
                <input type="color" name="nav_text" id="c_nav_text" value="<?= htmlspecialchars($curText) ?>"
                       oninput="livePreview()">
                <span>Site name text color in the nav</span>
            </div>
        </div>

        <button type="submit" name="save_branding" class="btn btn-primary">Save Branding</button>
        <a href="builder.php" class="btn btn-back">Cancel</a>
    </form>
</div>

<script>
function livePreview() {
    var nav    = document.getElementById('preview-nav');
    var brand  = document.getElementById('preview-brand');
    var accent = document.getElementById('preview-accent-btn');
    nav.style.background    = document.getElementById('c_nav_bg').value;
    nav.style.borderBottom  = '1px solid ' + document.getElementById('c_nav_border').value;
    brand.style.color       = document.getElementById('c_nav_text').value;
    accent.style.background = document.getElementById('c_accent').value;
}

function previewLogo(input) {
    var wrap = document.getElementById('preview-logo-wrap');
    if (!input.files || !input.files[0]) return;
    var reader = new FileReader();
    reader.onload = function(e) {
        var img = document.getElementById('preview-logo-img');
        if (!img) {
            img = document.createElement('img');
            img.id = 'preview-logo-img';
            img.style.cssText = 'max-height:28px;max-width:100px;object-fit:contain;';
            img.alt = '';
            wrap.appendChild(img);
        }
        img.src = e.target.result;
    };
    reader.readAsDataURL(input.files[0]);
}
</script>
</body>
</html>
